import React, { useEffect } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import "../globals.css";
import ReduxProvider from "@/redux/provider";

import Topbar from "@/components/Topbar";
import Bottombar from "@/components/Bottombar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "fusionchat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <ReduxProvider>
            <div className="container">
              <Topbar />
                {children}
              <Bottombar />
            </div>
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
