import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { redirect } from "next/navigation";

import "../globals.css";
import Topbar from "@/components/Topbar";
import LeftSidebar from "@/components/LeftSidebar";
import Bottombar from "@/components/Bottombar";
import { currentUser } from "@clerk/nextjs";
import { fetchUsers } from "@/lib/actions/user.actions";
import { User } from "@prisma/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "fusionchat",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser();

  if (!user) redirect("/sign-in");

  const users = await fetchUsers();
  if (!users.length) redirect("/sign-up");

  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <div className="container">
            <Topbar />
            <LeftSidebar users={users} userId={user.id} username={user.username ? user.username : ''} />
            <section className="main-container">
              <div className="w-full">{children}</div>
            </section>
            <Bottombar />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
